import "./globals.css";
import Header from "@/component/Header/header";
import Footer from "@/component/Footer/footer"

export const metadata = {
  title: "India #1 Career Counselling & Career",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`pt-12 md:pt-12`}
      ><Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
